export const PERMISSIONS = {
  USERS_MANAGE: 'platform.users.manage',
  ORGANIZATION_MANAGE: 'platform.organization.manage',
  AUDIT_READ: 'platform.audit.read',
  NOTIFICATIONS_MANAGE: 'platform.notifications.manage',
  SMTP_MANAGE: 'platform.smtp.manage',
  CRM_ACCESS: 'sales.crm.access',
  CRM_PERMANENT_DELETE: 'sales.crm.permanent-delete',
  INVENTORY_ACCESS: 'operations.inventory.access',
  INVENTORY_MANAGE: 'operations.inventory.manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS),
  HR: [PERMISSIONS.USERS_MANAGE],
  OPERATIONS: [PERMISSIONS.INVENTORY_ACCESS, PERMISSIONS.INVENTORY_MANAGE],
  EMPLOYEE: [],
  SALES: [PERMISSIONS.CRM_ACCESS],
  MANAGEMENT: [
    PERMISSIONS.CRM_ACCESS,
    PERMISSIONS.INVENTORY_ACCESS,
    PERMISSIONS.AUDIT_READ,
  ],
  HEAD: [
    PERMISSIONS.CRM_ACCESS,
    PERMISSIONS.INVENTORY_ACCESS,
    PERMISSIONS.INVENTORY_MANAGE,
  ],
  MANAGER: [
    PERMISSIONS.CRM_ACCESS,
    PERMISSIONS.INVENTORY_ACCESS,
    PERMISSIONS.INVENTORY_MANAGE,
  ],
  STAFF: [PERMISSIONS.CRM_ACCESS, PERMISSIONS.INVENTORY_ACCESS],
} as const;
